apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: my-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: image-registry.openshift-image-registry.svc:5000/my-echo-server/echo-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080